version: '3'
services:
  dev-workstation:
    image: "sysdiglabs/mc-pi-dev"
    container_name: "mc-pi-dev"
    volumes:
      - "./src:/usr/src/app"
    tty: true
    stdin_open: true
    restart: always
    links:
     - minecraft-server
  minecraft-server:
    image: "itzg/minecraft-server"
    container_name: "mc-pi-srv"
    ports:
      - "25565:25565"
      - "4711:4711"
    volumes:
      - "./data:/data"
      - "./plugins:/plugins"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.11.2"
    tty: true
    stdin_open: true
    restart: always